#!/usr/bin/env bash
# enable-autopilot.sh — ensure the go-stablenet project has autonomous
# (bypassPermissions) Claude Code settings so the coding-agent pipeline runs
# WITHOUT permission prompts. Idempotent: if already configured → pass;
# otherwise generate/merge (preserving any existing permissions.allow).
#
# IMPORTANT TIMING: Claude Code loads the permission mode at SESSION START.
# This script must run BEFORE `claude` launches in the project — it cannot
# flip an already-running session, and a plugin/hook cannot escalate
# permissions mid-session. Use coding-agent.sh (the launcher) which runs this
# first, or run it as part of setup.
set -euo pipefail

abs() { ( cd "$1" 2>/dev/null && pwd ); }
CKS_ROOT="$(abs "$(dirname "${BASH_SOURCE[0]}")/..")"
GSN="$(abs "${GO_STABLENET_ROOT:-$CKS_ROOT/../go-stablenet}")"
[ -n "$GSN" ] && [ -d "$GSN" ] || { echo "ERROR: go-stablenet not found (set GO_STABLENET_ROOT)" >&2; exit 1; }

SETTINGS="$GSN/.claude/settings.local.json"
mkdir -p "$GSN/.claude"

# Idempotent check + merge (preserve other keys / existing allow list).
SETTINGS="$SETTINGS" python3 - <<'PY'
import json, os, sys

path = os.environ["SETTINGS"]
try:
    with open(path) as f:
        data = json.load(f)
except FileNotFoundError:
    data = {}
except json.JSONDecodeError as e:
    sys.exit(f"ERROR: {path} is not valid JSON ({e}); fix it first.")

perms = data.get("permissions", {})
if not isinstance(perms, dict):
    sys.exit('ERROR: existing "permissions" is not an object; refusing to overwrite.')

already = perms.get("defaultMode") == "bypassPermissions" and data.get("skipDangerousModePermissionPrompt") is True
if already:
    print("autopilot: already configured → pass")
    sys.exit(0)

perms["defaultMode"] = "bypassPermissions"
perms.setdefault("allow", [])          # keep whatever is there; don't clobber
data["permissions"] = perms
data["skipDangerousModePermissionPrompt"] = True

with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(f"autopilot: generated bypassPermissions config → {path}")
PY

# Make sure the personal/local settings file is never committed.
GI="$GSN/.gitignore"
if [ -f "$GI" ] && ! grep -qxF ".claude/settings.local.json" "$GI" 2>/dev/null; then
  printf '\n# Claude Code personal/local settings (autonomous bypassPermissions; never commit)\n.claude/settings.local.json\n' >> "$GI"
  echo "autopilot: added .claude/settings.local.json to $GI"
fi
