// Command cks-glossary-gen builds a project's vocab.Glossary YAML by
// scanning that project's entries/*.yaml under docs/domain-knowledge.
//
// Each scanned entry contributes one Glossary entry: its korean_aliases
// and english_aliases together become the matchable aliases, its
// code_keywords (deduplicated, order preserved) become the canonical
// keyword list, and the entry's id is recorded under canonical for
// provenance.
//
// By default the generator includes only entries with
// status: verified — the same gate ckv build uses. Pass --status to
// override, e.g. --status=all when iterating during development.
//
// Usage:
//
//	cks-glossary-gen \
//	    -project docs/domain-knowledge/projects/go-stablenet \
//	    -out    docs/domain-knowledge/projects/go-stablenet/glossary.yaml \
//	    -status verified
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/0xmhha/code-knowledge-system/internal/vocab"
)

// entryFile is the subset of every entry YAML the generator cares about.
// We unmarshal lazily — unknown fields are tolerated so a schema bump
// that doesn't touch these fields does not break the generator.
type entryFile struct {
	ID             string   `yaml:"id"`
	Status         string   `yaml:"status"`
	KoreanAliases  []string `yaml:"korean_aliases"`
	EnglishAliases []string `yaml:"english_aliases"`
	CodeKeywords   []string `yaml:"code_keywords"`
}

// glossaryFile is the on-disk shape of a vocab.Glossary plus a single
// canonical-tracking field per entry. The shape matches vocab.Load
// exactly except for the canonical field, which the loader tolerates.
type glossaryFile struct {
	Version int                 `yaml:"version"`
	Entries []glossaryFileEntry `yaml:"entries"`
}

type glossaryFileEntry struct {
	Aliases      []string `yaml:"aliases"`
	Canonical    string   `yaml:"canonical"`
	CodeKeywords []string `yaml:"code_keywords"`
}

func main() {
	var (
		projectDir = flag.String("project", "", "project directory (contains entries/ subdirectory)")
		outPath    = flag.String("out", "", "output glossary.yaml path (default: <project>/glossary.yaml)")
		statusGate = flag.String("status", "verified", "include only entries with this status (verified | needs_verification | draft | all)")
		dryRun     = flag.Bool("dry-run", false, "print stats to stderr without writing the output file")
	)
	flag.Parse()

	if *projectDir == "" {
		fmt.Fprintln(os.Stderr, "cks-glossary-gen: -project is required")
		flag.Usage()
		os.Exit(2)
	}
	if *outPath == "" {
		*outPath = filepath.Join(*projectDir, "glossary.yaml")
	}
	entriesDir := filepath.Join(*projectDir, "entries")
	files, err := filepath.Glob(filepath.Join(entriesDir, "*.yaml"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "cks-glossary-gen: glob: %v\n", err)
		os.Exit(1)
	}
	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "cks-glossary-gen: no entries found at %s\n", entriesDir)
		os.Exit(1)
	}
	sort.Strings(files)

	out := glossaryFile{Version: 1}
	var skipped, included int
	for _, f := range files {
		var e entryFile
		buf, err := os.ReadFile(f)
		if err != nil {
			fmt.Fprintf(os.Stderr, "cks-glossary-gen: read %s: %v\n", f, err)
			os.Exit(1)
		}
		if err := yaml.Unmarshal(buf, &e); err != nil {
			fmt.Fprintf(os.Stderr, "cks-glossary-gen: parse %s: %v\n", f, err)
			os.Exit(1)
		}
		if !statusIncluded(e.Status, *statusGate) {
			skipped++
			continue
		}
		ge, ok := buildGlossaryEntry(e)
		if !ok {
			skipped++
			continue
		}
		out.Entries = append(out.Entries, ge)
		included++
	}

	fmt.Fprintf(os.Stderr, "cks-glossary-gen: included=%d skipped=%d (gate=%s)\n", included, skipped, *statusGate)

	// Round-trip validate: feed the result through vocab.New so any
	// generator bug that produces a malformed glossary surfaces here,
	// not at the next cks-mcp boot.
	check := vocab.Glossary{Version: out.Version}
	for _, ge := range out.Entries {
		check.Entries = append(check.Entries, vocab.Entry{
			Aliases:      ge.Aliases,
			Canonical:    ge.Canonical,
			CodeKeywords: ge.CodeKeywords,
		})
	}
	if _, err := vocab.New(check); err != nil {
		fmt.Fprintf(os.Stderr, "cks-glossary-gen: vocab.New round-trip failed: %v\n", err)
		os.Exit(1)
	}

	if *dryRun {
		return
	}

	yamlOut, err := yaml.Marshal(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cks-glossary-gen: marshal: %v\n", err)
		os.Exit(1)
	}
	header := "# Generated by cks-glossary-gen. Do not hand-edit — re-run the\n" +
		"# generator instead. Each glossary entry is sourced from the\n" +
		"# domain knowledge entry named under canonical.\n"
	if err := os.WriteFile(*outPath, append([]byte(header), yamlOut...), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "cks-glossary-gen: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
}

// statusIncluded reports whether a given entry status matches the gate.
// "all" includes everything; any other value is matched verbatim.
func statusIncluded(entryStatus, gate string) bool {
	if gate == "all" {
		return true
	}
	return entryStatus == gate
}

// buildGlossaryEntry assembles one glossary entry from a domain knowledge
// entry. Returns false when the entry contributes nothing matchable —
// either it has no aliases at all, or it has no code_keywords to map
// aliases onto. Empty / whitespace-only fields are filtered out, and
// duplicates within each list are collapsed while preserving order.
func buildGlossaryEntry(e entryFile) (glossaryFileEntry, bool) {
	aliases := dedupNonEmpty(append(append([]string{}, e.KoreanAliases...), e.EnglishAliases...))
	keywords := dedupNonEmpty(e.CodeKeywords)
	if len(aliases) == 0 || len(keywords) == 0 {
		return glossaryFileEntry{}, false
	}
	return glossaryFileEntry{
		Aliases:      aliases,
		Canonical:    e.ID,
		CodeKeywords: keywords,
	}, true
}

func dedupNonEmpty(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}
