package query

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// AliasMap maps a "human" phrase (often Korean or domain-vague) to a
// list of "code" keywords the embedder is more likely to match.
//
// Example:
//
//	"0번 블록"        → [genesis, genesis_block, GenesisAlloc]
//	"합의 알고리즘"   → [consensus, wbft, WBFT]
//	"시스템 컨트랙트" → [system contract, systemcontracts, SystemContracts]
//
// Used by ExpandQuery to widen the intent string at query time. The
// raw intent stays first so semantic ordering isn't disturbed; aliases
// are appended in a bracket-tagged trailer so the embedder treats them
// as auxiliary context.
//
// The map can be hand-curated (testdata/stablenet/glossary.yaml) or
// auto-generated by a glossary loader.
type AliasMap map[string][]string

// AliasFile is the on-disk YAML shape. We keep the top-level `aliases`
// key explicit so future additions (e.g., `metadata`, `version`) can
// land without breaking the loader.
type AliasFile struct {
	Aliases AliasMap `yaml:"aliases"`
}

// LoadAliasMap reads a glossary YAML and returns the parsed map.
// Returns nil + nil error when path is empty — callers can pass the
// CLI flag through unconditionally and the no-flag case stays a no-op.
// Empty `aliases` block is treated the same as no file (nil return).
func LoadAliasMap(path string) (AliasMap, error) {
	if strings.TrimSpace(path) == "" {
		return nil, nil
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("alias: read %s: %w", path, err)
	}
	var af AliasFile
	if err := yaml.Unmarshal(raw, &af); err != nil {
		return nil, fmt.Errorf("alias: parse %s: %w", path, err)
	}
	if len(af.Aliases) == 0 {
		return nil, nil
	}
	return af.Aliases, nil
}

// ExpandQuery widens intent with any alias entry whose key appears as
// a substring of intent. Output shape:
//
//	"<intent> [aliases: <kw1>, <kw2>, ...]"
//
// Returned intent is identical to input when:
//   - aliases is nil or empty
//   - no alias key appears in intent
//
// The trailer is deterministic: alias keys are matched in sorted order
// and matched-keyword lists are deduplicated + sorted before joining.
// Determinism matters for the per-query footprint fingerprint
// (query.embed sub-span) so two runs of the same intent produce the
// same trace fingerprint.
//
// Why substring match (not exact / token-aware): the intent is
// free-form natural language, often Korean with spaces / particles
// ("0번 블록의", "합의 알고리즘이"). Substring covers the common case;
// false positives are rare for the curated glossary we ship.
func ExpandQuery(intent string, aliases AliasMap) string {
	if len(aliases) == 0 {
		return intent
	}

	// Deterministic key iteration: sort the alias keys so matched
	// keywords land in a stable order regardless of map insertion.
	keys := make([]string, 0, len(aliases))
	for k := range aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	seen := make(map[string]struct{})
	var matched []string
	for _, k := range keys {
		if k == "" || !strings.Contains(intent, k) {
			continue
		}
		for _, kw := range aliases[k] {
			kw = strings.TrimSpace(kw)
			if kw == "" {
				continue
			}
			if _, dup := seen[kw]; dup {
				continue
			}
			seen[kw] = struct{}{}
			matched = append(matched, kw)
		}
	}
	if len(matched) == 0 {
		return intent
	}
	sort.Strings(matched)
	return fmt.Sprintf("%s [aliases: %s]", intent, strings.Join(matched, ", "))
}
