// Package setup turns the knowledge-setup sequence — build the graph index,
// build the vector index aligned to it, verify the two agree — into a typed,
// machine-runnable plan. It replaces the per-project shell scripts that used
// to encode this sequence with hardcoded paths.
//
// The engines are driven through their CLIs as subprocesses (the same
// execution model the fused server's index tool has always used): build
// failures stay isolated from the calling process, and cancellation is a
// process kill. The package deliberately imports no engine internals — the
// CLI flags used here are the compatibility contract, and the boundary check
// enforces the isolation.
package setup

import (
	"fmt"
	"os"
	"path/filepath"
)

// Options parameterizes one knowledge-setup plan.
type Options struct {
	// Src is the source tree to index. Required.
	Src string
	// Out is the dataset root; the graph index lands in Out/graph and the
	// vector index in Out/vector. Required.
	Out string

	// GraphBin / VectorBin are the engine CLI binaries. Empty values fall
	// back to "ckg" and "ckv" resolved on PATH (the binary names the engine
	// makefiles produce).
	GraphBin  string
	VectorBin string

	// Graph enrichment inputs (optional): governance policy and
	// security-pattern YAML passed through to the graph build.
	PolicyFile          string
	SecurityPatternFile string

	// Vector build knobs (optional). Embedder "" lets the vector CLI pick
	// its default; OllamaURL is exported as CKV_OLLAMA_ENDPOINT.
	Embedder  string
	ModelName string
	EmbedDim  int
	OllamaURL string
	// VectorPolicy is the vector chunk-categorization policy YAML.
	VectorPolicy string

	// SkipVector builds only the graph index (and skips alignment
	// verification, which needs both).
	SkipVector bool

	// FilelistConfig is an optional filelist-gen config (a pack's
	// filelist.yaml). When set, the plan first derives the build-scope file
	// list into Out/files-from.json and passes it to both engine builds via
	// --files-from, so the dataset scope is computed — not curated — and its
	// provenance ships with the dataset.
	FilelistConfig string
	// FilelistBin is the filelist-gen CLI. Empty falls back to
	// "filelist-gen" resolved on PATH.
	FilelistBin string

	// DomainKnowledge is a project's domain-knowledge directory (project.yaml,
	// subsystems.yaml, entries/). When set, the plan re-derives the three
	// artifacts that are a pure function of those entries — the embedding
	// corpus, the graph governance policy, and the alias glossary — into
	// DerivedDir before the engine builds consume them.
	//
	// Deriving them per run is the point: these used to be generated by hand
	// and committed, so an entry added months later left the policy and the
	// glossary describing a codebase that no longer existed, with nothing
	// failing to say so.
	DomainKnowledge string
	// DerivedDir is where the domain artifacts land. Empty defaults to
	// "generated" beside the domain-knowledge directory.
	DerivedDir string
	// CodeRoot is the working tree the project's authoritative_docs resolve
	// against. Unset is only viable for a project that declares none — the
	// export step fails rather than shipping a corpus without them.
	CodeRoot string
	// GlossaryFile is the committed alias glossary rendered from the same
	// entries. The fused server reads it at query time to bridge a user's
	// wording to the identifiers in the code, so the build does not consume
	// it — it only checks that it still matches the entries.
	GlossaryFile string
	// FlowCorpus is a curated flow-corpus JSONL embedded alongside the code
	// chunks. Unlike the three derived artifacts this one is hand-authored,
	// so it is consumed straight from the pack.
	FlowCorpus string
	// Domain tool CLIs. Empty values fall back to the names the system
	// makefile produces, resolved on PATH.
	DomainExportBin string
	DomainSyncBin   string
	GlossaryGenBin  string
}

// GraphDir / VectorDir are the per-engine data directories under Out.
func (o Options) GraphDir() string  { return filepath.Join(o.Out, "graph") }
func (o Options) VectorDir() string { return filepath.Join(o.Out, "vector") }

// FilesFromPath is where a derived build-scope list lands (and is read from)
// when FilelistConfig is set — inside the dataset, next to the indexes, so
// the scope provenance travels with the data.
func (o Options) FilesFromPath() string { return filepath.Join(o.Out, "files-from.json") }

// derivedRoot is where the domain artifacts land. They are project-level, not
// source-tree-level: the same entries describe every checkout of the project,
// so they sit beside the pack rather than inside one dataset. (The build-scope
// list is the opposite — it comes from one tree's build closure, so it lives
// in the dataset.)
func (o Options) derivedRoot() string {
	if o.DerivedDir != "" {
		return o.DerivedDir
	}
	return filepath.Join(filepath.Dir(o.DomainKnowledge), "generated")
}

// DomainCorpusDir is the rendered embedding corpus. It is the only domain
// artifact written here; the policy and the glossary are committed and merely
// checked against their entries (VerifyDerivedFresh).
func (o Options) DomainCorpusDir() string { return filepath.Join(o.derivedRoot(), "domain-corpus") }

// Step is one unit of the plan: either a subprocess (Cmd non-empty) or an
// internal verification (Verify non-nil).
type Step struct {
	ID    string
	Title string
	Cmd   []string // argv; nil for internal steps
	Env   []string // extra environment (KEY=VALUE), appended to the parent env
	// Verify runs an in-process check for internal steps. It may emit
	// non-fatal findings through the provided callback and returns an error
	// only when the step must fail the plan.
	Verify func(emit func(Event)) error
}

// Plan is the ordered step list for one setup run.
type Plan struct {
	Steps []Step
}

// BuildPlan assembles the canonical knowledge-setup sequence:
//
//  1. graph-build   — <graph-bin> build --src SRC --out OUT/graph [enrichment]
//  2. vector-build  — <vector-bin> build --src SRC --out OUT/vector --ckg OUT/graph [...]
//  3. verify-align  — read both manifests, assert same src commit and that
//     the vector index recorded the graph's coordinate pin
//
// The graph build is incremental by definition (the engine reuses its cache
// when OUT/graph already holds a usable manifest), so the same plan serves
// first-time setup and update runs.
func BuildPlan(o Options) (Plan, error) {
	if o.Src == "" {
		return Plan{}, fmt.Errorf("setup: Src is required")
	}
	if o.Out == "" {
		return Plan{}, fmt.Errorf("setup: Out is required")
	}
	graphBin := o.GraphBin
	if graphBin == "" {
		graphBin = "ckg"
	}
	vectorBin := o.VectorBin
	if vectorBin == "" {
		vectorBin = "ckv"
	}

	var steps []Step
	if o.DomainKnowledge != "" {
		exportBin, syncBin, glossaryBin := o.DomainExportBin, o.DomainSyncBin, o.GlossaryGenBin
		if exportBin == "" {
			exportBin = "cks-domain-export"
		}
		if syncBin == "" {
			syncBin = "cks-domain-sync"
		}
		if glossaryBin == "" {
			glossaryBin = "cks-glossary-gen"
		}
		exportCmd := []string{exportBin, "-project", o.DomainKnowledge, "-out", o.DomainCorpusDir()}
		if o.CodeRoot != "" {
			exportCmd = append(exportCmd, "-code-root", o.CodeRoot)
		}
		// The corpus is the one artifact that is genuinely derived here: it
		// is large, nobody reads it by hand, and the vector build consumes it
		// directly. The policy and the glossary stay committed and are only
		// checked — see VerifyDerivedFresh for why.
		steps = append(steps, Step{
			ID:    "domain-export",
			Title: "Render the domain-knowledge embedding corpus",
			Cmd:   exportCmd,
		})
		if o.PolicyFile != "" {
			argv := []string{syncBin, "-entries", o.DomainKnowledge, "-ckv-out", os.DevNull, "-ckg-out"}
			steps = append(steps, Step{
				ID:    "policy-fresh",
				Title: "Check the governance policy against the domain entries",
				Verify: func(emit func(Event)) error {
					return VerifyDerivedFresh("policy-fresh", "the governance policy", argv, o.PolicyFile, emit)
				},
			})
		}
		if o.GlossaryFile != "" {
			argv := []string{glossaryBin, "-project", o.DomainKnowledge, "-out"}
			steps = append(steps, Step{
				ID:    "glossary-fresh",
				Title: "Check the alias glossary against the domain entries",
				Verify: func(emit func(Event)) error {
					return VerifyDerivedFresh("glossary-fresh", "the alias glossary", argv, o.GlossaryFile, emit)
				},
			})
		}
	}
	if o.FilelistConfig != "" {
		filelistBin := o.FilelistBin
		if filelistBin == "" {
			filelistBin = "filelist-gen"
		}
		steps = append(steps, Step{
			ID:    "filelist-derive",
			Title: "Derive the build-scope file list",
			Cmd: []string{filelistBin,
				"-src", o.Src,
				"-config", o.FilelistConfig,
				"-out", o.FilesFromPath()},
		})
	}

	graphCmd := []string{graphBin, "build", "--src", o.Src, "--out", o.GraphDir()}
	if o.FilelistConfig != "" {
		graphCmd = append(graphCmd, "--files-from", o.FilesFromPath())
	}
	if o.PolicyFile != "" {
		graphCmd = append(graphCmd, "--policy-file", o.PolicyFile)
	}
	if o.SecurityPatternFile != "" {
		graphCmd = append(graphCmd, "--security-pattern-file", o.SecurityPatternFile)
	}
	steps = append(steps, Step{
		ID:    "graph-build",
		Title: "Build the graph index",
		Cmd:   graphCmd,
	})

	if !o.SkipVector {
		vectorCmd := []string{vectorBin, "build", "--src", o.Src, "--out", o.VectorDir(), "--ckg", o.GraphDir()}
		if o.FilelistConfig != "" {
			vectorCmd = append(vectorCmd, "--files-from", o.FilesFromPath())
		}
		if o.Embedder != "" {
			vectorCmd = append(vectorCmd, "--embedder="+o.Embedder)
		}
		if o.ModelName != "" {
			vectorCmd = append(vectorCmd, "--model-name="+o.ModelName)
		}
		if o.EmbedDim > 0 {
			vectorCmd = append(vectorCmd, fmt.Sprintf("--embed-dim=%d", o.EmbedDim))
		}
		if o.VectorPolicy != "" {
			vectorCmd = append(vectorCmd, "--policy", o.VectorPolicy)
		}
		if o.DomainKnowledge != "" {
			vectorCmd = append(vectorCmd, "--docs", o.DomainCorpusDir())
		}
		if o.FlowCorpus != "" {
			vectorCmd = append(vectorCmd, "--flow-corpus", o.FlowCorpus)
		}
		var env []string
		if o.OllamaURL != "" {
			env = append(env, "CKV_OLLAMA_ENDPOINT="+o.OllamaURL)
		}
		// Fail fast on an unusable Ollama backend before the long build.
		if o.Embedder == "ollama" {
			url, model := o.OllamaURL, o.ModelName
			steps = append(steps, Step{
				ID:    "vector-preflight",
				Title: "Preflight the Ollama embedder",
				Verify: func(emit func(Event)) error {
					return PreflightOllama(url, model, emit)
				},
			})
		}
		steps = append(steps,
			Step{
				ID:    "vector-build",
				Title: "Build the vector index aligned to the graph",
				Cmd:   vectorCmd,
				Env:   env,
			},
			Step{
				ID:    "verify-align",
				Title: "Verify graph/vector alignment",
				Verify: func(emit func(Event)) error {
					return VerifyAlignment(o.GraphDir(), o.VectorDir(), emit)
				},
			},
		)
		if o.DomainKnowledge != "" || o.FlowCorpus != "" {
			opts := o
			steps = append(steps, Step{
				ID:    "verify-content",
				Title: "Verify the declared inputs reached the index",
				Verify: func(emit func(Event)) error {
					return VerifyContent(opts, emit)
				},
			})
		}
	}
	return Plan{Steps: steps}, nil
}
