#!/usr/bin/env python3
"""Generate the stage/next/all-remaining view from the canonical 30 worklist rows."""
import argparse
from collections import Counter
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parent.parent
WORKLIST = ROOT / 'docs/spec-driven/EXECUTION-WORKLIST.md'
OUTPUT = ROOT / 'docs/spec-driven/EXECUTION-STATUS.md'
EXPECTED = {f'{stage}-{i:02}' for stage, total in [('B0',9),('B1',8),('C0',6),('C1',7)] for i in range(1,total+1)}
LABELS = {'done':'✅ 완료','progress':'🟡 진행','waiting':'⏳ 대기'}


def render(raw):
    tasks = []
    for line in raw.splitlines():
        if not re.match(r'^\| (B[01]|C[01])-\d\d \|', line):
            continue
        fields = [f.strip() for f in line.strip('|').split('|')]
        if len(fields) != 5:
            raise ValueError('worklist row must have five columns')
        qid, priority, task, condition, status = fields
        if status.startswith(('검증 완료', '구현 검증 완료')): state = 'done'
        elif status.startswith(('진행', '도구 준비', '도구 검증 완료')): state = 'progress'
        elif status in ['대기','사람 검토 대기']: state = 'waiting'
        else: raise ValueError('unclassified status: ' + qid)
        tasks.append((qid,priority,task,status,state))
    if {t[0] for t in tasks} != EXPECTED or len(tasks) != len(EXPECTED):
        raise ValueError('all 30 worklist IDs must appear exactly once')
    counts = Counter(t[4] for t in tasks)
    gate_lines = re.findall(r'<!-- official-gates: (.*?) -->', raw)
    if len(gate_lines) != 1:
        raise ValueError('one explicit official gate ledger required')
    gates = json.loads(gate_lines[0])
    if set(gates) != {'B0','B1','C0','C1'} or any(v not in {'pending','pass','fail','inconclusive'} for v in gates.values()):
        raise ValueError('invalid official gate ledger')
    for stage, verdict in gates.items():
        if verdict != 'pending' and any(t[4] != 'done' for t in tasks if t[0].startswith(stage)):
            raise ValueError('declared official gate closed with unfinished tasks: ' + stage)
    closed = sum(v != 'pending' for v in gates.values())
    lines = ['# 작업 진행 현황판', '', '<!-- Generated by scripts/update-execution-status.py; edit EXECUTION-WORKLIST.md. -->', '',
      f"전체 30개: **✅ 완료 {counts['done']} · 🟡 진행 {counts['progress']} · ⏳ 대기 {counts['waiting']}**. 공식 품질 게이트 **B0/B1/C0/C1 {closed}/4 판정 완료**.", '',
      '완료 수는 작업리스트의 명시된 구현/검증 범위다. 공식 게이트 verdict는 별도 원장을 읽으며 판정 완료가 pass를 의미하지 않는다. 도구 준비·과거 구조 진단을 품질 합격으로 합산하지 않는다. 최종 근거와 종료 조건은 [작업리스트](./EXECUTION-WORKLIST.md)를 따른다.', '',
      '**단계:** 구현 재검증 ✅ → B0 입력 검토/기준선 🟡 → B1 비교 준비 🟡 → C0 공식 실패 수정 ⏳ → C1 최종 재평가/출시 ⏳', '',
      '| 단계 | 완료 | 진행 | 대기 | 현재 위치 |', '|---|---:|---:|---:|---|']
    position = {'B0':'범위·프로토콜·동적 입력·의미 사실·STV2 사람 결정 대기', 'B1':'어댑터 완료; 보고·안전 제어 도구 준비, 공식 비교/사람 판정 대기',
                'C0':'공식 B1 관측 실패 분류 대기; 구조 FIX-01–16은 별도 기록', 'C1':'패키지/고지/복구 preview 준비; 공식 품질·운영 결정 대기'}
    for stage in ['B0','B1','C0','C1']:
        c = Counter(t[4] for t in tasks if t[0].startswith(stage))
        lines.append(f"| {stage} | {c['done']} | {c['progress']} | {c['waiting']} | {('작업 종료; verdict=' + gates[stage]) if c['done'] == sum(t[0].startswith(stage) for t in tasks) else position[stage]} |")
    lines += ['', '**바로 다음 독립 작업:** raw CKV 후보 순위와 F-01 exact/budget 판정의 보고 연결 준비(B0-06/B1-04).', '',
      '**승인 도착 시 최우선:** B0-01/02/03/05·STV2-01 결정 기록 → source/pack/semantic/scope/K 동결 → B0-07 새 strict 빌드/감사 → B0-08/09 공식 기준선.', '',
      f"**남은 전체 작업 {30-counts['done']}개**", '', '| ID | 상태 | 우선순위·선행 | 남은 작업 |', '|---|---|---|---|']
    for qid, priority, task, status, state in tasks:
        if state != 'done':
            lines.append(f'| {qid} | {LABELS[state]} | {priority} | {task} |')
    lines += ['', '**추가 결정·환경 범위**', '',
      '- STV2-01: 정적 v2 날짜/subsystem·정수 K10과 실제 runtime/계측 결합 승인(B0-06).',
      '- OP-01 역할/권한, OP-02 배포 scope/schema, OP-03 공개 키/독립 신뢰 경로, OP-04 개인 키 보관·접근·백업, OP-05 교체·폐기·유출 대응.',
      '- OP-06 original C/header·전이 native·고지 적합성, OP-07 지원 플랫폼·실모델·대규모 비용, OP-08 최종 운영 백업·실패 전환·복구 담당/실행.',
      '- native Linux amd64 실제 모델/운영 환경, 최종 패키지·마이그레이션/복구·지원/known limits와 출시 판정(C1-04–07).',
      '- raw CKV 후보 순위와 전체 동적 가족 오라클, 독립 최종 실행, 답변·주장·정책·기권·사람 검토 비용 판정(B0/B1).', '',
      '매 턴 마지막 보고에 현재 단계, 다음 작업, 위 미완료 전체 목록을 함께 표시한다. 변경 후 이 현황판을 갱신하고 `python3 scripts/update-execution-status.py --check`로 작업리스트와 동기화한다.', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render(WORKLIST.read_text())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            raise SystemExit('execution status is stale; run scripts/update-execution-status.py')
        print('execution status: synchronized (30 tasks)')
    else:
        OUTPUT.write_text(text)
        print('execution status: updated (30 tasks)')


if __name__ == '__main__':
    main()
